server:
  port: 9191

spring:
  application:
    name: gateway
  security:
    oauth2:
      client:
        registration:
          identity:
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/auth/callback/{registrationId}"
            scope: openid,profile,email
        provider:
          identity:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
      resourceserver:
        jwt:
          issuer-uri: ${spring.security.oauth2.client.provider.identity.issuer-uri}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI}
  instance:
    preferIpAddress: true